primehalo_primepostrevisions_view:
    path: /revisions/view/{post_id}
    defaults: { _controller: primehalo.primepostrevisions.controller:view }
    requirements:
        post_id: \d+

primehalo_primepostrevisions_delete:
    path: /revisions/delete/{revision_id}
    defaults: { _controller: primehalo.primepostrevisions.controller:delete }
    requirements:
        revision_id: \d+

primehalo_primepostrevisions_restore:
    path: /revisions/restore/{revision_id}
    defaults: { _controller: primehalo.primepostrevisions.controller:restore }
    requirements:
        revision_id: \d+
